### ISSUE TITLE
Corrections in BCube addressing code

### ISSUE THREAD

**Issue by mohittahiliani** [shravya-ks/ns-3-tcp-prague#4]
Correct the suggestions provided in [this commit](https://github.com/shravya-ks/ns-3-tcp-prague/commit/93b65f146395deaeb96d358b46da87f958a5e7e3)

**Comment by mohittahiliani** [comment]
@shravya-ks - is this issue addressed?

**Comment by shravya-ks** [comment]
I have addressed all comments except one. This is regarding ns_log_function, other topology helpers dont have ns_log_function. Do I need to add?

**Comment by mohittahiliani** [comment]
Yes, better to have even though others don't

**Comment by shravya-ks** [comment]
Ok sir, will add it.

**Comment by shravya-ks** [comment]
Sir,
I have addressed all your issues on githhub. Let me know if anything is
pending in bcube.
